language: php
php:
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: ac726f3a4c2197e7fff2a66ec5aa11941634f99c43b259548334d416fd883535

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=ac726f3a4c2197e7fff2a66ec5aa11941634f99c43b259548334d416fd883535  ./vendor/bin/test-reporter